export type Language = 'rust' | 'go';
export const LANGUAGES: readonly Language[] = ['rust', 'go'];

// FR-032 (ADR 0006 D13): the C2 catalogs sit outside the chain (chainPosition null); E1 adds
// essentials at position 1.
export const CATALOGS = [
  { code: 'lab', sliceBy: 'language', chainPosition: null },
  { code: 'quests', sliceBy: 'language', chainPosition: null },
  { code: 'cores', sliceBy: 'domain', chainPosition: null },
] as const;

export type SystemsDomain = 'lowlevel' | 'infra' | 'play' | 'pc';
export const SYSTEMS_DOMAINS: readonly SystemsDomain[] = ['lowlevel', 'infra', 'play', 'pc'];

export type Catalog = 'lab' | 'quests' | SystemsDomain;

// Key order the legacy catalogs published; the oracle observes it (Object.keys, JSON.stringify).
export const EXERCISE_KEY_ORDER = {
  lab: [
    'id',
    'language',
    'topicId',
    'topic',
    'stage',
    'kind',
    'minutes',
    'imports',
    'visual',
    'sources',
    'level',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'starter',
    'solution',
    'tests',
    'hints',
    'review',
    'transfer',
    'prediction',
  ],
  quests: [
    'id',
    'language',
    'topicId',
    'topic',
    'stage',
    'level',
    'challengeType',
    'kind',
    'minutes',
    'imports',
    'visual',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'starter',
    'solution',
    'tests',
    'hints',
    'review',
    'transfer',
    'prediction',
    'sources',
  ],
  lowlevel: [
    'id',
    'language',
    'topicId',
    'topic',
    'stage',
    'level',
    'kind',
    'minutes',
    'visual',
    'imports',
    'intro',
    'why',
    'prediction',
    'sources',
    'title',
    'objective',
    'instructions',
    'hints',
    'review',
    'transfer',
    'starter',
    'solution',
    'tests',
  ],
  infra: [
    'id',
    'language',
    'topicId',
    'topic',
    'workshopId',
    'stage',
    'level',
    'kind',
    'challengeType',
    'minutes',
    'visual',
    'imports',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'hints',
    'review',
    'transfer',
    'prediction',
    'sources',
    'starter',
    'solution',
    'tests',
  ],
  play: [
    'id',
    'language',
    'stage',
    'level',
    'topicId',
    'topic',
    'kind',
    'minutes',
    'imports',
    'visual',
    'sources',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'hints',
    'review',
    'prediction',
    'transfer',
    'starter',
    'solution',
    'tests',
  ],
  pc: [
    'stage',
    'level',
    'kind',
    'minutes',
    'visual',
    'imports',
    'topic',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'hints',
    'review',
    'transfer',
    'prediction',
    'sources',
    'id',
    'language',
    'topicId',
    'starter',
    'solution',
    'tests',
  ],
} as const satisfies Record<Catalog, readonly string[]>;

export type ExerciseKey = (typeof EXERCISE_KEY_ORDER)[Catalog][number];

export const OPTIONAL_EXERCISE_KEYS: Record<Catalog, readonly string[]> = {
  lab: ['level'],
  quests: [],
  lowlevel: [],
  infra: [],
  play: [],
  pc: [],
};
