// Forma de los catálogos que publica curriculum.json: lenguajes, dominios de Sistemas y el
// orden de claves de cada catálogo de ejercicios.
export type Language = 'rust' | 'go';
export const LANGUAGES: readonly Language[] = ['rust', 'go'];

// FR-032 (ADR 0006 D13): the C2 catalogs sit outside the chain (chainPosition null); E1 adds
// essentials at position 1.
export const CATALOGS = [
  { code: 'lab', sliceBy: 'language', chainPosition: null },
  { code: 'quests', sliceBy: 'language', chainPosition: null },
  { code: 'cores', sliceBy: 'domain', chainPosition: null },
] as const;

export type SystemsDomain = 'lowlevel' | 'infra' | 'play' | 'pc';
export const SYSTEMS_DOMAINS: readonly SystemsDomain[] = ['lowlevel', 'infra', 'play', 'pc'];

// Catálogo publicado al que pertenece un ejercicio: RUST_LAB/GO_LAB, RUST_QUESTS/GO_QUESTS o
// uno de los SYSTEMS_<DOMINIO>_LABS.
export type Catalog = 'lab' | 'quests' | SystemsDomain;

// Orden de claves con que cada catálogo legacy publicaba sus ejercicios: las vistas legacy y
// el oráculo lo observan (Object.keys, JSON.stringify). Sale de `add` (recorrido),
// `defineQuest` (desafíos) y de los literales de cada dominio de núcleos. El orden del YAML
// no importa; una clave que no figure acá es un error.
export const EXERCISE_KEY_ORDER = {
  lab: [
    'id',
    'language',
    'topicId',
    'topic',
    'stage',
    'kind',
    'minutes',
    'imports',
    'visual',
    'sources',
    'level',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'starter',
    'solution',
    'tests',
    'hints',
    'review',
    'transfer',
    'prediction',
  ],
  quests: [
    'id',
    'language',
    'topicId',
    'topic',
    'stage',
    'level',
    'challengeType',
    'kind',
    'minutes',
    'imports',
    'visual',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'starter',
    'solution',
    'tests',
    'hints',
    'review',
    'transfer',
    'prediction',
    'sources',
  ],
  lowlevel: [
    'id',
    'language',
    'topicId',
    'topic',
    'stage',
    'level',
    'kind',
    'minutes',
    'visual',
    'imports',
    'intro',
    'why',
    'prediction',
    'sources',
    'title',
    'objective',
    'instructions',
    'hints',
    'review',
    'transfer',
    'starter',
    'solution',
    'tests',
  ],
  infra: [
    'id',
    'language',
    'topicId',
    'topic',
    'workshopId',
    'stage',
    'level',
    'kind',
    'challengeType',
    'minutes',
    'visual',
    'imports',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'hints',
    'review',
    'transfer',
    'prediction',
    'sources',
    'starter',
    'solution',
    'tests',
  ],
  play: [
    'id',
    'language',
    'stage',
    'level',
    'topicId',
    'topic',
    'kind',
    'minutes',
    'imports',
    'visual',
    'sources',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'hints',
    'review',
    'prediction',
    'transfer',
    'starter',
    'solution',
    'tests',
  ],
  pc: [
    'stage',
    'level',
    'kind',
    'minutes',
    'visual',
    'imports',
    'topic',
    'title',
    'intro',
    'why',
    'objective',
    'instructions',
    'hints',
    'review',
    'transfer',
    'prediction',
    'sources',
    'id',
    'language',
    'topicId',
    'starter',
    'solution',
    'tests',
  ],
} as const satisfies Record<Catalog, readonly string[]>;

// Toda clave que algún catálogo publica: cada una necesita su comprobación en exercises.ts.
export type ExerciseKey = (typeof EXERCISE_KEY_ORDER)[Catalog][number];

// Sólo el recorrido tiene ejercicios sin nivel (75 de 100 por lenguaje).
export const OPTIONAL_EXERCISE_KEYS: Record<Catalog, readonly string[]> = {
  lab: ['level'],
  quests: [],
  lowlevel: [],
  infra: [],
  play: [],
  pc: [],
};
